# Generated by Django 3.0.5 on 2025-03-07 04:30

from django.db import migrations, models
import djongo.models.fields
import invoice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('seller_company_name', models.CharField(max_length=255)),
                ('seller_address', models.TextField()),
                ('seller_contact', models.EmailField(max_length=254)),
                ('seller_phone', models.CharField(max_length=20)),
                ('seller_tax_id', models.CharField(max_length=50)),
                ('buyer_company_name', models.CharField(max_length=255)),
                ('buyer_address', models.TextField()),
                ('buyer_contact', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(max_length=20)),
                ('buyer_tax_id', models.CharField(max_length=50)),
                ('items', djongo.models.fields.ArrayField(blank=True, model_container=invoice.models.Item, null=True)),
                ('payment_terms', models.CharField(max_length=255)),
            ],
        ),
    ]
